### ISSUE TITLE
[台服]新版台版無法取得資料?

### ISSUE THREAD

**Issue by willysunny** [xxzl0130/rsyars#1]
![image](https://user-images.githubusercontent.com/5907852/72897909-f8952c00-3d5d-11ea-9b3b-34985ea77e04.png)

代理設置完，連線有反應，也正常進入遊戲畫面

但是就這樣了，沒有剩下資料

已嘗試各種房間/介面，依然無法有資料請求的狀態

**Comment by xxzl0130** [comment]
代理设置完后需要重新打开游戏，从最初的登陆界面登陆进去才会有数据。  另外台服可能需要参考README中的特殊解决方案进行操作才能顺利完成。-------- 原始邮件 --------发件人： Sunny <notifications@github.com>日期： 2020年1月22日周三 21:29收件人： xxzl0130/rsyars <rsyars@noreply.github.com>抄送： Subscribed <subscribed@noreply.github.com>主    题： [xxzl0130/rsyars] [台服]新版台版無法取得資料? (#1)

代理設置完，連線有反應，也正常進入遊戲畫面

但是就這樣了，沒有剩下資料

已嘗試各種房間/介面，依然無法有資料請求的狀態

**Comment by willysunny** [comment]
有，你可以看的到藍色那串就是在登入時產生出來的
我嘗試用手機+模擬器都一樣
都有重新登入遊戲，也都甚至嘗試用不同的登入方式(FB+天下)
都是可以進入遊戲，但是就是沒有輸出

(最後那個index.php就是成功進入主頁時會出來的東西)

**Comment by xxzl0130** [comment]
我明白了，txwy.tw大概相当于是台湾的渠道服，稍后我会将这个域名加入代理过滤列表里，应该就可用正常使用了。届时我会再回复issue以通知你。

**Comment by xxzl0130** [comment]
刚才说错了，应该是台服更换了域名。  
请试试附件中的版本。  

[rsyars.zip](https://github.com/xxzl0130/rsyars/files/4104789/rsyars.zip)

**Comment by willysunny** [comment]
一樣，我甚至開了Verbose，都沒有額外訊息

**Comment by xxzl0130** [comment]
不应该啊。能麻烦你发一下完整的日志吗，最好是上传上来程序同文件夹下的log文件。

**Comment by willysunny** [comment]
請麻煩看一下信箱，我已把Log轉發給您了

**Comment by willysunny** [comment]
好吧，我把路由器和數據機兩個都重啟過後就可以了 ¯\_(ツ)_/¯
